### ISSUE TITLE
strange error when imposing the pressure BC

### ISSUE THREAD

**Issue by p-costa** [maxcuda/CaNS#1]
Hi,

I am trying to run the code with the default setup.h90 and bc.h90 files on a Tesla K80, with CUDA & MPI; one MPI task.

The case is compiled with the following flags (pgi 18.10):
`OPT := -O0 -Mcuda`
`OTH := -DEPHC -DEPA2A -DTIMING -DUSE_CUDA -DUSE_NVTX -DGPU_MPI`
(If I instead use `-Mcuda=cc70`, the bug reported [here](https://www.pgroup.com/userforum/viewtopic.php?t=2376) is triggered)

I find that if I don't add a synchronization step in between setting up the pressure BCs, i.e.:

    call set_bc(cbc(0,3),0,n(3),3,.true.,bc(0,3),dzc(0)   ,p)
    !@cuf ierr = cudaDeviceSynchronize()
    call set_bc(cbc(1,3),1,n(3),3,.true.,bc(1,3),dzc(n(3)),p)

the code will crash at the first call of subroutine `boundp`:

> [t03n02:30004] *** Process received signal ***
> [t03n02:30004] Signal: Bus error (7)
> [t03n02:30004] Signal code: Non-existant physical address (2)
> [t03n02:30004] Failing at address: 0x8105d9c200

When I add this synchronization step the code seems to run fine.

I don't understand why this synchronization is required, since something very similar is done in the subroutine `bounduvw` and there seems to be no problem there.

Thanks in advance!

Best,
Pedro

**Comment by maxcuda** [comment]
Could you try -Mcuda=cc35 ?
K80s are quite old, there may also be issues with managed memory.

**Comment by p-costa** [comment]
Thanks!

With -Mcuda=cc35 I don't have [this issue](https://www.pgroup.com/userforum/viewtopic.php?t=2376) anymore.

But the code still crashes without that sync in `boundp`.

**Comment by romerojosh** [comment]
I believe the extra synchronization is _required_ when using managed/unified memory with pre-Pascal cards (compute capability less than 6.0). See this forum post:  https://devtalk.nvidia.com/default/topic/1044349/cuda-programming-and-performance/cudamallocmanaged-clarification-needed/post/5298422/#5298422

It sounds like on older architectures without page faulting, a `cudaDeviceSynchronize()` is required to safely access memory buffers on the host which were used in GPU kernels. I think `boundp` accesses memory through the host when MPI routines are invoked.

**Comment by p-costa** [comment]
Thanks! I understand. Doesn't seem like a big problem for recent models.

I still find it a bit intriguing, because I add a synchronization step in between two calls that do not seem to access the host memory. And in the subroutine that uses MPI calls it seems that there is proper synchronization. I lost my interactive node for the K80 so I cannot test it further today.

**Comment by p-costa** [comment]
Hi again,

The issue was in the access of array `dzc` in the call of `set_bc`. This array is not accessed in `bounduvw` for this setup, but it is in `boundp`.

~It's interesting because from my understanding `dzc` is on the device (also with `cudaMemAdviseSetReadMostly`).~ (this was wrong)

If I substitute this line:
```
    if(ctype.eq.'N'.and.stag) then
      if(    ibound.eq.0) then
        factor = -dr*factor
      elseif(ibound.eq.1) then
        factor =  dr*factor
      endif
      sgn    = 1.d0
    endif
```
with this (since with this setup `factor` is zero anyway):
```
    if(ctype.eq.'N'.and.stag) then
      if(    ibound.eq.0) then
        factor = 0.*factor
      elseif(ibound.eq.1) then
        factor =  0.*factor
      endif
      sgn    = 1.d0
    endif
```
I don't need the sync anymore for it to work.

Pedro

**Comment by romerojosh** [comment]
If I'm following correctly, there was indeed a host access of an array previously used without a sync then that was causing the issue? If so, this confirms the cause of the issue.

I think the only truly _safe_ way to run with managed memory on pre-Pascal devices is to run with `CUDA_LAUNCH_BLOCKING=1`, which will cause all kernel launches to be synchronous w.r.t the host.

**Comment by p-costa** [comment]
> If I'm following correctly, there was indeed a host access of an array previously used without a sync then that was causing the issue? If so, this confirms the cause of the issue.

Yes, that seems to be the case. `dzc` is touched on the host memory without synchronization. Since I'm a bit new to this I was not sure, but now I am. I'll close the issue. Thanks!
